@startuml Eternal Quest
static class Program {
    +{static} goals: List<Goal>
    +{static} Main(args:string): void
    +{static} CreateGoal(): void
    +{static} ReadInt(): int
}
abstract class Goal {
    #name: string
    #description: string
    #completed: Boolean
    #points: int
    +Goal(name:string, description:string, points:int)
    +{abstract} Serialize(): string
    +{abstract} Completed(): Boolean
    +{abstract} GetTotalPoints(): int
    +{abstract} MarkComplete(): void
}
class SimpleGoal {
    +SimpleGoal(name: string, description: string, points: int)
}
class EternalGoal {
    -timesCompleted: int
    +EternalGoal(name: string, description: string, points: int)
}
class ChecklistGoal {
    -bonus: int
    -completions: int
    -targetCompletions: int
    +ChecklistGoal(name: string, description: string, points:int, targetCompletions:int, bonus:int )

}

Goal <|-- SimpleGoal
Goal <|-- EternalGoal
Goal <|-- ChecklistGoal

Program "1" o-- "many" Goal
