@startuml Dungeon
static class Program {
    _name: string;
}
abstract class Encounter {

}
class SimpleEncounter {

}
class BossEncounter {

}
class CompoundEncounter {

}
class Player {

}
class Item {

}
class TextImage {

}

Encounter <|-- SimpleEncounter
Encounter <|-- BossEncounter
Encounter <|-- CompoundEncounter
Program "1" o-- "many" Encounter
Program "1" o-- "many" Player
Player "1" o-- "many" Item
Encounter o-- TextImage
Program o-- TextImage
Encounter o-- Item



